config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'home#index'
  devise_for :users
  resources :domains
  get '/domains/update/:id', to: 'domains#update'
  list = [%w[dns dnsrrs], %w[header headers], %w[mail mailconfigs], %w[port ports], %w[tls tlsconfigs], %w[whois whoisrecords]]
  list.each do |obj|
    get "/#{obj[0]}/:id", to: "#{obj[1]}#show"
    get "/#{obj[0]}/update/:id", to: "#{obj[1]}#update"
    get "/guide/#{obj[0]}", to: "guide##{obj[0]}"
  end
  get '/guide', to: 'guide#index'
  get '/tools', to: 'tools#index'
  get '/tools/base64', to: 'base64#index'
  post '/tools/base64/encode', to: 'base64#show'
  post '/tools/base64/decode', to: 'base64#show'
  get '/tools/csr', to: 'csr#index'
  post '/tools/csr', to: 'csr#show'
  get '/tools/dig', to: 'dig#index'
  post '/tools/dig', to: 'dig#show'
  get '/tools/dnspropagation', to: 'dnspropagation#index'
  post '/tools/dnspropagation', to: 'dnspropagation#show'
  get '/tools/password', to: 'pass#index'
  post '/tools/password', to: 'pass#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dnsrr.rb
# frozen_string_literal: true

class Dnsrr < ApplicationRecord
  belongs_to :domain
end

app/models/domain.rb
# frozen_string_literal: true

class Domain < ApplicationRecord
  belongs_to :user
  has_many :dnsrrs, dependent: :destroy
  has_many :headers, dependent: :destroy
  has_many :ports, dependent: :destroy
  has_many :tlsconfigs, dependent: :destroy
  has_one :whoisrecord, dependent: :destroy
  validates :fqdn, format: { with: /\A[a-z0-9][a-z0-9.-]+[a-z]\z/, message: 'Domain names only' }
end

app/models/header.rb
# frozen_string_literal: true

class Header < ApplicationRecord
  belongs_to :domain
end

app/models/password.rb
# frozen_string_literal: true

class Password < ApplicationRecord
  validates :length, length: { in: 1..2 }, numericality: { only_integer: true }
end

app/models/port.rb
# frozen_string_literal: true

class Port < ApplicationRecord
  belongs_to :domain, dependent: :delete
  validates :number, numericality: { only_integer: true }, presence: true
end

app/models/tlsconfig.rb
# frozen_string_literal: true

class Tlsconfig < ApplicationRecord
  belongs_to :domain
  validates :version, inclusion: { in: %w[SSLv3 TLSv1 TLSv1_1 TLSv1_2] }
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :domains, dependent: :destroy
end

app/models/whoisrecord.rb
# frozen_string_literal: true

class Whoisrecord < ApplicationRecord
  belongs_to :domain
end

app/controllers/csr_controller.rb
# frozen_string_literal: true

# Decode CSR fields
class CsrController < ApplicationController
  # GET /tools/csr
  def index; end

  # POST /tools/csr
  def show
    @csr = params[:csr]
    begin
      rqst = OpenSSL::X509::Request.new(@csr).subject
    rescue StandardError
      rqst = Hash('CSR' => 'Not valid')
    end
    @csrhash = rqst.to_a
  end
end

app/controllers/dig_controller.rb
# frozen_string_literal: true

# Web Dig
class DigController < ApplicationController
  # GET /tools/dig
  def index; end

  # POST /tools/dig
  def show
    fqdn = params[:fqdn]
    dnstype = %w[A AAAA CAA CNAME MX NS PTR SOA SRV TXT]
    @result = {}
    dnstype.each do |thetype|
      @result[thetype] = []
      res = Dnsruby::DNS.new(timeouts: 1)
      res.each_resource(fqdn, thetype) do |rr|
        @result[thetype].push(rr.rdata.to_s)
      end
    end
  end
end

app/controllers/dnsrrs_controller.rb
# frozen_string_literal: true

# DNS Records
class DnsrrsController < GreponController
  before_action :set_domain

  # GET /dns/update/1
  def update
    du = DnsrrsUpdater.new(@domain)
    du.refresh
    redirect_to action: 'show', id: @domain.id
  end

  # GET /dns/1
  def show
    set_rrs
    set_lastupdate
  end

  private

  def set_domain
    @domain = Domain.find(params[:id])
  end

  def set_rrs
    @rrs = @domain.dnsrrs
  end

  def set_lastupdate
    @lastupdate = if @rrs.first
                    @rrs.first.updated_at.to_formatted_s(:short)
                  else
                    'Never'
                  end
  end
end

app/helpers/csr_helper.rb
# frozen_string_literal: true

module CsrHelper
end

app/helpers/dig_helper.rb
# frozen_string_literal: true

module DigHelper
end

app/helpers/dnsrrs_helper.rb
# frozen_string_literal: true

module DnsrrsHelper
end

app/helpers/domains_helper.rb
# frozen_string_literal: true

module DomainsHelper
end

app/helpers/guide_helper.rb
# frozen_string_literal: true

module GuideHelper
end

app/helpers/headers_helper.rb
# frozen_string_literal: true

module HeadersHelper
end

app/helpers/home_helper.rb
# frozen_string_literal: true

module HomeHelper
end

app/helpers/pass_helper.rb
# frozen_string_literal: true

module PassHelper
end

app/helpers/ports_helper.rb
# frozen_string_literal: true

module PortsHelper
end

app/helpers/tlsconfigs_helper.rb
# frozen_string_literal: true

module TlsconfigsHelper
end

app/helpers/whois_helper.rb
# frozen_string_literal: true

module WhoisHelper
end

app/views/dnsrrs/show.html.erb
<p>
<%= link_to 'Back', domain_path %>
</p>

<p><strong><%= @domain.fqdn %></strong></p>
<p>
  Last update : <%= @lastupdate %>
  <%= link_to ('<i class="fa fa-refresh"></i>').html_safe, "/dns/update/#{@domain.id}" %>
</p>

<p>
  <p class='title'>DNS records</p>
</p>

<div class="table-container">
  <table class='table is-striped is-hoverable is-fullwidth'>
    <thead>
      <tr>
        <th>Type</th>
        <th>Value</th>
      </tr>
    </thead>
    <tr>
      <td>A</td>
      <td>
        <ul>
          <% @rrs.where(dnstype: 'A').each do |rr| %>
            <li><%= rr.value %></li>
          <% end %>
        </ul>
      </td> 
    </tr>
    <tr>
      <td>AAAA</td>
      <td>
        <ul>
          <% @rrs.where(dnstype: 'AAAA').each do |rr| %>
            <li><%= rr.value %></li>
          <% end %>
        </ul>
      </td> 
    </tr>
    <tr>
      <td>AXFR</td>
      <td>
        <ul>
          <% @rrs.where(dnstype: 'AXFR').each do |rr| %>
            <li><%= rr.value %></li>
          <% end %>
        </ul>
      </td> 
    </tr>
    <tr>
      <td>CAA</td>
      <td>
        <ul>
          <% @rrs.where(dnstype: 'CAA').each do |rr| %>
            <li><%= rr.value %></li>
          <% end %>
        </ul>
      </td> 
    </tr>
    <tr>
      <td>CNAME</td>
      <td>
        <ul>
          <% @rrs.where(dnstype: 'CNAME').each do |rr| %>
            <li><%= rr.value %></li>
          <% end %>
        </ul>
      </td> 
    </tr>
    <tr>
      <td>DMARC</td>
      <td>
        <ul>
          <% @rrs.where(dnstype: 'DMARC').each do |rr| %>
            <li><%= rr.value %></li>
          <% end %>
        </ul>
      </td> 
    </tr>
    <tr>
      <td>MX</td>
      <td>
        <ul>
          <% @rrs.where(dnstype: 'MX').each do |rr| %>
            <li><%= rr.value %></li>
          <% end %>
        </ul>
      </td> 
    </tr>
    <tr>
      <td>NS</td>
      <td>
        <ul>
          <% @rrs.where(dnstype: 'NS').each do |rr| %>
            <li><%= rr.value %></li>
          <% end %>
        </ul>
      </td> 
    </tr>
    <tr>
      <td>PTR</td>
      <td>
        <ul>
          <% @rrs.where(dnstype: 'PTR').each do |rr| %>
            <li><%= rr.value %></li>
          <% end %>
        </ul>
      </td> 
    </tr>
    <tr>
      <td>SRV</td>
      <td>
        <ul>
          <% @rrs.where(dnstype: 'SRV').each do |rr| %>
            <li><%= rr.value %></li>
          <% end %>
        </ul>
      </td> 
    </tr>
    <tr>
      <td>TXT</td>
      <td>
        <ul>
          <% @rrs.where(dnstype: 'TXT').each do |rr| %>
            <li><%= rr.value %></li>
          <% end %>
        </ul>
      </td> 
    </tr>
  </table>
</div>